import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Platform } from 'react-native';

export const generateEyeHealthReport = async (results: any[], stats: any) => {
  const html = `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
        <style>
          body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #333; }
          .header { text-align: center; margin-bottom: 50px; border-bottom: 2px solid #007AFF; padding-bottom: 20px; }
          .title { font-size: 32px; color: #007AFF; margin-bottom: 5px; }
          .subtitle { font-size: 14px; color: #666; }
          .section { margin-bottom: 40px; }
          .section-title { font-size: 20px; font-weight: bold; margin-bottom: 15px; color: #111; }
          .stats-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 30px; }
          .stat-box { background: #F2F2F7; padding: 20px; border-radius: 12px; }
          .stat-value { font-size: 24px; font-weight: bold; color: #007AFF; }
          .stat-label { font-size: 12px; color: #666; text-transform: uppercase; }
          table { width: 100%; border-collapse: collapse; margin-top: 10px; }
          th { text-align: left; padding: 12px; background: #007AFF; color: white; }
          td { padding: 12px; border-bottom: 1px solid #EEE; }
          .status { padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; }
          .status-normal { background: #E1F8EB; color: #34C759; }
          .status-attention { background: #FFF9E6; color: #FF9500; }
          .status-concern { background: #FFEBEB; color: #FF3B30; }
          .footer { margin-top: 50px; font-size: 10px; color: #999; text-align: center; border-top: 1px solid #EEE; padding-top: 20px; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="title">EyeCare Pro</div>
          <div class="subtitle">Comprehensive Eye Health Clinical Summary</div>
          <div class="subtitle">Generated on: ${new Date().toLocaleDateString()}</div>
        </div>

        <div class="section">
          <div class="section-title">Habit Metrics</div>
          <div class="stats-grid">
            <div class="stat-box">
              <div class="stat-value">${stats.dailyScreenTime || '4.5'} hrs</div>
              <div class="stat-label">Avg Daily Screen Time</div>
            </div>
            <div class="stat-box">
              <div class="stat-value">${stats.breakCompliance || '82'}%</div>
              <div class="stat-label">20-20-20 Rule Compliance</div>
            </div>
            <div class="stat-box">
              <div class="stat-value">${stats.eyeStrainScore || '14'}</div>
              <div class="stat-label">Digital Strain Score</div>
            </div>
            <div class="stat-box">
              <div class="stat-value">${stats.blinkRate || '12'} bpm</div>
              <div class="stat-label">Avg Blinks Per Minute</div>
            </div>
          </div>
        </div>

        <div class="section">
          <div class="section-title">Screening Test History</div>
          <table>
            <thead>
              <tr>
                <th>Test Type</th>
                <th>Date</th>
                <th>Score</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              ${results.map(r => `
                <tr>
                  <td>${r.testType}</td>
                  <td>${r.date}</td>
                  <td>${r.score}%</td>
                  <td><span class="status status-${r.status}">${r.status.toUpperCase()}</span></td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        </div>

        <div class="section">
          <div class="section-title">Clinical Disclaimer</div>
          <p style="font-size: 12px; line-height: 1.6; color: #666;">
            This document is generated by the EyeCare Pro application and is intended for informational and screening purposes only. 
            It is NOT a formal medical diagnosis or prescription. Users are strongly advised to share this report with a licensed 
            ophthalmologist or optometrist for a professional comprehensive eye examination.
          </p>
        </div>

        <div class="footer">
          EyeCare Pro Security Verified • E2E Encrypted Data Source • HIPAA Compliant Storage Patterns
        </div>
      </body>
    </html>
  `;

  try {
    const { uri } = await Print.printToFileAsync({ html });
    if (Platform.OS === 'ios') {
      await Sharing.shareAsync(uri);
    } else {
      await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'EyeCare Pro Health Report' });
    }
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw error;
  }
};
